language: php

dist: trusty
sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

git:
    depth: 1

compiler:
    - gcc
    - clang

env:
  global:
       - ZEND_DONT_UNLOAD_MODULES=1
        - USE_ZEND_ALLOC=0
        - REPORT_EXIT_STATUS=1

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    apt: true
    timeout: 604800

install:
    - phpenv config-rm xdebug.ini || true
    - $(phpenv which phpize)
    - ./configure --with-php-config=$(phpenv which php-config) --enable-psr
    - make --silent -j"$(getconf _NPROCESSORS_ONLN)"

before_script:
    - ulimit -c unlimited -S || true

script:
    - make test

notifications:
    email:
        on_success: never
        on_failure: never
