language: php

dist: trusty
sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

git:
    depth: 1

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - valgrind
            - gdb

notifications:
    email:
        on_success: never
        on_failure: never

env:
    global:
        - ZEND_DONT_UNLOAD_MODULES=1
        - USE_ZEND_ALLOC=0
        - REPORT_EXIT_STATUS=1
        - NO_INTERACTION=1
        - TEST_PHP_ARGS="--show-diff"
    matrix:
        - CC="gcc"
        - CC="clang"

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    exclude:
        - env: CC="gcc"
          compiler: clang
        - env: CC="clang"
          compiler: gcc

cache:
    apt: true
    timeout: 604800

install:
    - phpenv config-rm xdebug.ini || true
    - $(phpenv which phpize)
    - ./configure --with-php-config=$(phpenv which php-config) --enable-psr
    - make --silent -j"$(getconf _NPROCESSORS_ONLN)"

before_script:
    - ulimit -c unlimited -S || true

script:
    - $(phpenv which php) -d extension=$(pwd)/modules/psr.so --ri psr
    - make test
    - make install
    - echo "extension=psr.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && php --ri psr
